# Change these first
owner: sflwa # Your GitHub organization or username, where this repository lives
repo: sflwa-uptime # The name of this repository

sites:
  - name: Temple Beth Orr
    url: https://www.templebethorr.org
  - name: Temple Torat Emet
    url: https://www.templetoratemet.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sflwa-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SFLWA Uptime Monitoring
  introTitle: "*Website Uptime Monitoring for SFLWA Clients"
  introMessage: We hope everything is green
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
